apiVersion: v1
kind: ServiceAccount
metadata:
  name: instance-metric-collector
  namespace: instance-platform
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: instance-metric-collector
subjects:
  - kind: ServiceAccount
    name: instance-metric-collector
    namespace: instance-platform
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
