apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpc-metric-collector
  namespace: keti-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpc-metric-collector
  namespace: keti-system
subjects:
- kind: ServiceAccount
  name: hpc-metric-collector
  namespace: keti-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: hpc-metric-collector
  namespace: keti-system
  labels:
    name: hpc-metric-collector
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32544
    protocol: TCP
  selector:
    name: hpc-metric-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpc-metric-collector
  namespace: keti-system
spec:
  selector:
    matchLabels:
      name: hpc-metric-collector
  replicas: 1
  template:
    metadata:
      labels:
        name: hpc-metric-collector
    spec:
      serviceAccountName: hpc-metric-collector
      imagePullSecrets: 
      - name: regcred
      restartPolicy: Always
      containers:
      - name: hpc-metric-collector
        image: ketidevit2/hpc-metric-collector:v1.1
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DEBUGG_LEVEL
          value: "LEVEL1"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OpenCSD_METRIC_COLLECTOR_IP
          value: "10.0.4.85"
        - name: OpenCSD_METRIC_COLLECTOR_PORT
          value: "30003"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hpc-metric-collector-configmap
  namespace: keti-system
data:
  metric-collecting-cycle : "5"


